import { execFileSync } from 'child_process'

// Patterns that indicate AI-generated commits
const AI_PATTERNS = [
  /co-authored-by:\s*claude/i,
  /co-authored-by:\s*github-actions/i,
  /\u{1F916}/u, // 🤖
  /\[ai\]/i,
  /\[claude\]/i,
  /generated with \[claude/i,
  /generated by claude/i,
  /ai-generated/i,
  /claude code/i,
  /claude opus/i,
  /claude sonnet/i,
  /claude haiku/i,
  /anthropic/i,
  /co-authored-by:.*noreply@anthropic\.com/i,
]

function isAICommit(message, body) {
  const fullText = `${message}\n${body || ''}`.toLowerCase()
  return AI_PATTERNS.some((pattern) => pattern.test(fullText))
}

function parseNumstat(numstat) {
  let added = 0
  let removed = 0
  for (const line of numstat.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed) continue
    // Format: <added>\t<removed>\t<filename>
    // Binary files show "-\t-\t<filename>"
    const parts = trimmed.split('\t')
    if (parts.length < 2) continue
    const a = parseInt(parts[0], 10)
    const r = parseInt(parts[1], 10)
    if (!isNaN(a)) added += a
    if (!isNaN(r)) removed += r
  }
  return { added, removed }
}

function getCommits(repoPath, fromCommit, toRef) {
  const range = fromCommit ? `${fromCommit}..${toRef}` : toRef

  let logOutput
  try {
    logOutput = execFileSync(
      'git',
      [
        '-C', repoPath,
        'log',
        range,
        '--format=%H\x00%s\x00%b\x00END_COMMIT',
        '--no-merges',
      ],
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
    )
  } catch {
    return []
  }

  const commits = []
  const blocks = logOutput.split('END_COMMIT\n').filter(Boolean)

  for (const block of blocks) {
    const parts = block.split('\x00')
    if (parts.length < 3) continue
    const [hash, subject, body] = parts
    if (!hash || !hash.trim()) continue

    // Get numstat for this commit
    let numstatOutput = ''
    try {
      numstatOutput = execFileSync(
        'git',
        ['-C', repoPath, 'show', '--numstat', '--format=', hash.trim()],
        { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
      )
    } catch {
      numstatOutput = ''
    }

    const { added, removed } = parseNumstat(numstatOutput)
    const ai = isAICommit(subject, body)

    commits.push({
      hash: hash.trim(),
      subject: subject.trim(),
      ai,
      linesAdded: added,
      linesRemoved: removed,
    })
  }

  return commits
}

export function analyzeSession(repoPath, startCommit) {
  const commits = getCommits(repoPath, startCommit, 'HEAD')

  let aiAdded = 0
  let aiRemoved = 0
  let humanAdded = 0
  let humanRemoved = 0
  let aiCommits = 0
  let humanCommits = 0

  for (const commit of commits) {
    if (commit.ai) {
      aiAdded += commit.linesAdded
      aiRemoved += commit.linesRemoved
      aiCommits++
    } else {
      humanAdded += commit.linesAdded
      humanRemoved += commit.linesRemoved
      humanCommits++
    }
  }

  const totalAdded = aiAdded + humanAdded
  const totalRemoved = aiRemoved + humanRemoved
  const totalLines = totalAdded + totalRemoved

  // Multiplier: total lines / human lines
  // If human wrote 0 lines, avoid division by zero — use total as denominator
  const humanLines = humanAdded + humanRemoved
  const multiplier = humanLines > 0 ? totalLines / humanLines : totalLines > 0 ? Infinity : 1

  const aiRatio = totalLines > 0 ? (aiAdded + aiRemoved) / totalLines : 0

  return {
    commits,
    aiCommits,
    humanCommits,
    aiAdded,
    aiRemoved,
    humanAdded,
    humanRemoved,
    totalAdded,
    totalRemoved,
    totalLines,
    humanLines,
    aiRatio,
    multiplier,
  }
}

export function analyzeRepo(repoPath) {
  return analyzeSession(repoPath, null)
}
